### ISSUE TITLE
Change the cursor from pointer to default on the close button

### ISSUE THREAD

**Issue by taylorlapeyre** [atom/tabs#26]
Having the cursor become a "hand" when hovering over the close button on a tab looks very "web" and not very native. Instead, just use the default pointer and add a hoverstate to the close icon.

A rudimentary example can be seen by adding the following to your stylesheet:

``` less
.tab-bar .tab .close-icon {
  cursor: default;

  &:hover {
    color: #AAA !important;
  }
}
```

After doing this, closing tabs feels much snappier.
