### ISSUE TITLE
Tabs are created off screen

### ISSUE THREAD

**Issue by JLoppert** [atom/tabs#67]
Windows 7, Atom version 0.115.0

Opening a large number of files (21 <) causes new tabs to be opened off screen.

Ctrl + Tabbing through opened tabs does not bring the current tab on screen. 

![croppercapture 2](https://cloud.githubusercontent.com/assets/1620641/3574814/1735eeec-0b82-11e4-9384-5291d385bb47.Gif)

**Comment by zamicol** [comment]
I'm still experiencing issues with large number of tabs.  Should I open a new issue as a [Feature Request] for Chrome like tab behavior?

Tabs are cut off, and I want to be able to see all tabs at the same time on the same line.  

This is what I see:
![atom_tab_offscreen](https://cloud.githubusercontent.com/assets/5232965/23272878/28638980-f9ba-11e6-929c-7680c3726e87.png)

This is what I want (example from Chrome):
![chrome_tab_behavior](https://cloud.githubusercontent.com/assets/5232965/23272907/3d0b14a2-f9ba-11e6-8b66-e4063ed09ea7.png)

**Comment by simurai** [comment]
@zamicol In Chrome, if you have too many tabs to fit the space, they just disappear. So you have to remove a couple to see the ones that disappeared. Having the tabs bar scrollable, you at least can get to them without having to close other tabs.

Also, the tabs in the Atom Dark UI theme have a minimum width so that you can directly close a tab without having to select it first.

Maybe not that important for everyone. You could customize the tabs in your `style.less` file. Maybe something like below should be closer to Chrome:

```less
// Chrome style tabs for atom-dark-ui theme
.tab-bar {
  overflow-x: hidden;
  display: flex;
  flex-wrap: wrap;
}
.tab-bar .tab {
  min-width: 13px;
  flex: 1;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
}
.tab-bar .tab .title {
  flex: 1 1 16px;
  text-overflow: clip;
  text-align: center;
}
.tab-bar .tab .close-icon {
  position: relative;
}
.tab-bar .tab.active {
  flex: 1;
  width: initial;
}
.tab-bar .tab.active:hover .close-icon {
  position: absolute;
  background: inherit;
  left: 0;
  right: 0;
  text-align: center;
}
```

![tabs](https://cloud.githubusercontent.com/assets/378023/23288086/acb622fe-fa84-11e6-8dca-fff45f6007d4.gif)
