### ISSUE TITLE
[Feature Request] Flow too many tabs to multiple lines

### ISSUE THREAD

**Issue by fungilation** [atom/tabs#76]
One thing I notice from Webstorm that's great is it flows tabs onto 2 (or more?) lines when there's too many. This is a common occurrence I'm sure with many programmers having many files open, and tabs so crowded you can't read the filenames on the tabs anymore.

PS. Issue originally filed at https://github.com/atom/atom/issues/3260

**Comment by theblacklion** [comment]
@simurai Hmm seems to work fine except that my active tab is being crunched to its minimum size. Any idea to fix this?

**Comment by simurai** [comment]
@theblacklion What's the theme you're using? And by "being crunched to its minimum size", is it about `40px` so you only see a few characters?

**Comment by theblacklion** [comment]
@simurai "Spacegray Eighties" from the spacegray-eighties-ui package and "Base16" (Eighties, Dark) fromt he base16-syntax package. Yes, only some characters. Normally it would expand the active tab, but with this modification it rather tries to expand all other than the active tab :)

**Comment by simurai** [comment]
@theblacklion Ok, for "Spacegray Eighties" this should work:

```less
// Make tabs multi-row
.tab-bar {
  height: auto;
  flex-wrap: wrap;
  .tab,
  .tab.active {
    flex-basis: auto;
  }
}
```

**Comment by theblacklion** [comment]
@simurai Thanks - works much better :). But when switching to the last tab of the first row, it suddenly flows into the next row because of the appearing close button. I'm now using flex-basis: 10em; as a workaround. This does not happen if I just hover over the tabs. Any idea?

**Comment by simurai** [comment]
Hmm.. ya, there is some expanding on the active tab. But this should keep it at the same size:

```less
// Make tabs multi-row
.tab-bar {
  height: auto;
  flex-wrap: wrap;
  .tab,
  .tab.active {
    flex: 1 0 auto;
    height: 30px;
    line-height: 27px;
  }
  .tab .title,
  .tab.active .title {
    padding-right: 5px;
    position: relative;
    top: 1px;
  }
  .tab .close-icon,
  .tab.active .close-icon {
    line-height: 29px;
  }
}
```
